<?php

$referenceArray = array("Shine on you crazy diamond",
"Strangelove", "Purple Haze", "Wild World",
"The 2nd Law", "Propane Nightmares", "Almost Blue",
"Headphone Activist", "Hits From the Bong", "Man in the Mirror",
"Vicious Delicious", "Thelonious Monk", "Yellow Submarine",
"Pink Season", "Peter Gabriel", "Porter Robinson",
"DJ-JO", "Fhána", "The Mars Volta",
"ChouCho", "Aterisk", "King Crimson",
"Supercell", "The Baseballs", "Sasakure.UK",
"Little Mix - Power", "Chowdr", "Ziggy Stardust",
"Sakurabust", "CHiCO","Forever Autumn",
"Close to the Edge", "Dragonforce", "Dazzle Camouflage",
"Perturbator", "To the Top", "DJ Fresh",
"The Open Hour", "Bonfire", "2pac",
"Pegboard Nerds", "Subtact", "Roundabout",
"Meg & Dia", "Camo", "Krooked",
"Team Nekokan", "Feint", "Senya",
"Nat King Cole", "Nights in White Satin", "Afromania",
"Shawn Wasabi", "Sukkels", "Hollywood Undead",
"Plight", "ParagonX9", "Lake Bodom",
"Wolfgang A. M.", "Gavin G.", "Linkwood",
"Smash Mouth - All Star", "Nano", "Devil in Disguise",
"Poem for Everyone's Souls", "Bolero of Fire", "Guns 'n' Roses",
"Slash", "Sting", "De Do Do Do, De Da Da Da",
"Alphaville", "Bleach", "Bauhaus",
"(You Gotta) Fight For Your Right", "Bo Burnham", "A-ha",
"BLOODY STREAM", "Breakbot", "Cage the Elephant",
"Karma Chameleon", "Culture Code", "Girls Just Want To Have Fun",
"DIMMADUBSTEP", "You Spin Me Round (Like a Record)", "1979",
"Deep Purple", "DotEXE", "Droid Bishop - Nightland",
"So Are You", "Blasé Boys", "EDEN",
"Santana IV", "Purple Rain", "Eric Chevalier",
"Fever the Ghost", "FM-84", "El Huervo",
"100 ways", "Flamingosis", "Flux Pavilion",
"News of the World", "Kenji", "19-2000",
"Gotye", "Gregorian", "Holy Diver",
"Gopnik McBlyat", "The Lunar Republic", "Toby Fox",
"Haveluckgoodfun", "IAM", "Joey Bada$$",
"Stille Willem", "Kenny G.", "I Was Made For Loving You",
"Kultur - Until Later", "House of Dupree", "Boiler",
"Professional Rapper", "So Electric", "MAGIC!",
"Mando Diao", "Mr. Fijiwiji", "Ron Basejam",
"Ross From Friends", "Route 94", "SOS Band",
"Scattle", "Shigeo Sekito", "Sim Gretina",
"Stromae", "Eye of the Tiger", "This Must Be the Place",
"The Kite String Tangle", "The Half Blunt Prince", "Seven Nation Army",
"Afrojack", "Hot For Teacher", "BRADIO",
"Carpeter Brut", "Ella Usó Mi Cabeza Como Un Revólver",
"Rob Zombie - Dragula", "Notorious B.I.G.", "Tommy Jayden",
"Tuxedo", "Atlantis Love", "Oh!",
"Ice Ice Baby", "Walter Murphy & the Big Apple Band", "We Are Number One but it's in Japanese",
"Paint it, Black", "REO Speedwagon", "Kendrick Lamar",
"TenTemPiés", "Colour Haze", "Dio - Pain",
"Se vaikenee joka pelkää" 
);


$pickTitle = rand(0 , count($referenceArray) -1);
$title = $referenceArray[$pickTitle];

?>
